/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/cc1': RouteRecordInfo<'/posts/cc1', '/posts/cc1', Record<never, never>, Record<never, never>>,
    '/posts/Front-and-rear-ends': RouteRecordInfo<'/posts/Front-and-rear-ends', '/posts/Front-and-rear-ends', Record<never, never>, Record<never, never>>,
    '/posts/high-accuracy': RouteRecordInfo<'/posts/high-accuracy', '/posts/high-accuracy', Record<never, never>, Record<never, never>>,
    '/posts/java-serialization': RouteRecordInfo<'/posts/java-serialization', '/posts/java-serialization', Record<never, never>, Record<never, never>>,
    '/posts/javascript-1': RouteRecordInfo<'/posts/javascript-1', '/posts/javascript-1', Record<never, never>, Record<never, never>>,
    '/posts/JavaScript-es6-1': RouteRecordInfo<'/posts/JavaScript-es6-1', '/posts/JavaScript-es6-1', Record<never, never>, Record<never, never>>,
    '/posts/JavaScript-export': RouteRecordInfo<'/posts/JavaScript-export', '/posts/JavaScript-export', Record<never, never>, Record<never, never>>,
    '/posts/linux-java8': RouteRecordInfo<'/posts/linux-java8', '/posts/linux-java8', Record<never, never>, Record<never, never>>,
    '/posts/linux-maven': RouteRecordInfo<'/posts/linux-maven', '/posts/linux-maven', Record<never, never>, Record<never, never>>,
    '/posts/Maven-aliyun': RouteRecordInfo<'/posts/Maven-aliyun', '/posts/Maven-aliyun', Record<never, never>, Record<never, never>>,
    '/posts/my-software': RouteRecordInfo<'/posts/my-software', '/posts/my-software', Record<never, never>, Record<never, never>>,
    '/posts/MySQL-id-auto': RouteRecordInfo<'/posts/MySQL-id-auto', '/posts/MySQL-id-auto', Record<never, never>, Record<never, never>>,
    '/posts/pows': RouteRecordInfo<'/posts/pows', '/posts/pows', Record<never, never>, Record<never, never>>,
    '/posts/proxy-configuration': RouteRecordInfo<'/posts/proxy-configuration', '/posts/proxy-configuration', Record<never, never>, Record<never, never>>,
    '/posts/Python-reptile-1': RouteRecordInfo<'/posts/Python-reptile-1', '/posts/Python-reptile-1', Record<never, never>, Record<never, never>>,
    '/posts/security-burteforce-pikachu': RouteRecordInfo<'/posts/security-burteforce-pikachu', '/posts/security-burteforce-pikachu', Record<never, never>, Record<never, never>>,
    '/posts/security-fileUpload': RouteRecordInfo<'/posts/security-fileUpload', '/posts/security-fileUpload', Record<never, never>, Record<never, never>>,
    '/posts/security-RCE': RouteRecordInfo<'/posts/security-RCE', '/posts/security-RCE', Record<never, never>, Record<never, never>>,
    '/posts/security-setup-pikachu': RouteRecordInfo<'/posts/security-setup-pikachu', '/posts/security-setup-pikachu', Record<never, never>, Record<never, never>>,
    '/posts/security-SQLInjection': RouteRecordInfo<'/posts/security-SQLInjection', '/posts/security-SQLInjection', Record<never, never>, Record<never, never>>,
    '/posts/socks5-basic': RouteRecordInfo<'/posts/socks5-basic', '/posts/socks5-basic', Record<never, never>, Record<never, never>>,
    '/posts/vueForceUpdate': RouteRecordInfo<'/posts/vueForceUpdate', '/posts/vueForceUpdate', Record<never, never>, Record<never, never>>,
    '/posts/vul-fastjson': RouteRecordInfo<'/posts/vul-fastjson', '/posts/vul-fastjson', Record<never, never>, Record<never, never>>,
    '/posts/vul-shiro': RouteRecordInfo<'/posts/vul-shiro', '/posts/vul-shiro', Record<never, never>, Record<never, never>>,
    '/posts/vulnhub-Lampiao': RouteRecordInfo<'/posts/vulnhub-Lampiao', '/posts/vulnhub-Lampiao', Record<never, never>, Record<never, never>>,
    '/posts/vx-application-yakit': RouteRecordInfo<'/posts/vx-application-yakit', '/posts/vx-application-yakit', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
